CREATE TABLE Profile (
    EMAIL VARCHAR(100) PRIMARY KEY,
    PASSWORD VARCHAR(50) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DATEOFBIRTH DATE,
    GENDER VARCHAR(10),
    CITY VARCHAR(50),
    PINCODE VARCHAR(10),
    MOBILE VARCHAR(15)
);

-- Sample Data
INSERT INTO Profile (EMAIL, PASSWORD, NAME, DATEOFBIRTH, GENDER, CITY, PINCODE, MOBILE) 
VALUES ('john.doe@example.com', 'pass123', 'John Doe', '1998-05-12', 'Male', 'Mumbai', '400001', '9876543210');